# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_full <- function(L, lambda) {
    .Call(`_MissCP_soft_full`, L, lambda)
}

lambda_warm_up <- function(data_y, data_x, blocks, cv_index) {
    .Call(`_MissCP_lambda_warm_up`, data_y, data_x, blocks, cv_index)
}

lm_break_fit_block <- function(data_y, data_x, lambda, lambda2, max_iteration, tol, initial_phi, blocks, cv_index) {
    .Call(`_MissCP_lm_break_fit_block`, data_y, data_x, lambda, lambda2, max_iteration, tol, initial_phi, blocks, cv_index)
}

lm_partial_break_fit_block <- function(data_y, data_x, lambda, lambda2, max_iteration, tol, initial_phi, initial_phi_2, blocks, cv_index, fixed_index, nonfixed_index) {
    .Call(`_MissCP_lm_partial_break_fit_block`, data_y, data_x, lambda, lambda2, max_iteration, tol, initial_phi, initial_phi_2, blocks, cv_index, fixed_index, nonfixed_index)
}

